[build.environment]
GO_VERSION = "1.24.2"
HUGO_VERSION = "0.148.0"
NODE_VERSION = "22"
TZ = "America/Los_Angeles"
SECRETS_SCAN_OMIT_PATHS = "public/js/llm-config.js"

[build]
publish = "public"
command = "git config core.quotepath false && hugo --gc --minify && sed -i \"s/%%HF_API_TOKEN%%/$HF_API_TOKEN/g\" public/js/llm-config.js"
